name: SwiftLint

on:
  push:
    branches: [ main, dev ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - 'auto-clicker/**/*.swift'
  pull_request:
    branches: [ main, dev ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - 'auto-clicker/**/*.swift'

jobs:
  lint:
    name: Ensure project code standards are adhered to
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # - name: SwiftLint
      #   uses: norio-nomura/action-swiftlint@3.2.1
      # Okay this (strict mode) does work and I do prefer it, as it will fail the run if the code is not validating
      #  ~all~ rules, even warnings. I prefer this behaviour, as its more obvious something is wrong. In order to
      #  see what is wrong, under the PR go to the 'Files changed' tab, then scroll right to the bottom in which there
      #  is a sub-heading 'Unchanged files with check annotations (Beta)' in which I really wish these annotations were
      #  placed onto the main PR page.
      - name: SwiftLint (Strict)
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
